language: node_js
node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"

sudo: required
services:
  - docker

before_install:
  - aws ecr get-login
  - docker build -t slooker/linkmage
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push -t slooker/linkmage

